/*
 * Copyright (c) 2007, 2019 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3010 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.11.23 at 04:24:57 PM IST 
//


package com.sun.xml.registry.common.tools.bindings_v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.sun.xml.registry.common.tools.bindings_v3.Command;
import com.sun.xml.registry.common.tools.bindings_v3.JAXRClassificationScheme;
import com.sun.xml.registry.common.tools.bindings_v3.JAXRConcept;
import com.sun.xml.registry.common.tools.bindings_v3.Namepattern;


/**
 * <p>Java class for Command element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="Command">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}JAXRClassificationScheme" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}JAXRConcept" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}namepattern" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="commandname" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="path" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jaxrClassificationScheme",
    "jaxrConcept",
    "namepattern"
})
@XmlRootElement(name = "Command")
public class Command {

    @XmlElement(name = "JAXRClassificationScheme")
    protected List<JAXRClassificationScheme> jaxrClassificationScheme;
    @XmlElement(name = "JAXRConcept")
    protected List<JAXRConcept> jaxrConcept;
    protected List<Namepattern> namepattern;
    @XmlAttribute(required = true)
    protected String commandname;
    @XmlAttribute
    protected String path;

    /**
     * Gets the value of the jaxrClassificationScheme property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jaxrClassificationScheme property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJAXRClassificationScheme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXRClassificationScheme }
     * 
     * 
     */
    public List<JAXRClassificationScheme> getJAXRClassificationScheme() {
        if (jaxrClassificationScheme == null) {
            jaxrClassificationScheme = new ArrayList<JAXRClassificationScheme>();
        }
        return this.jaxrClassificationScheme;
    }

    /**
     * Gets the value of the jaxrConcept property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the jaxrConcept property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getJAXRConcept().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXRConcept }
     * 
     * 
     */
    public List<JAXRConcept> getJAXRConcept() {
        if (jaxrConcept == null) {
            jaxrConcept = new ArrayList<JAXRConcept>();
        }
        return this.jaxrConcept;
    }

    /**
     * Gets the value of the namepattern property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the namepattern property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNamepattern().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Namepattern }
     * 
     * 
     */
    public List<Namepattern> getNamepattern() {
        if (namepattern == null) {
            namepattern = new ArrayList<Namepattern>();
        }
        return this.namepattern;
    }

    /**
     * Gets the value of the commandname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommandname() {
        return commandname;
    }

    /**
     * Sets the value of the commandname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommandname(String value) {
        this.commandname = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
